title: <p align="center"> Chris Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/duynguyen7590/">LinkedIn</a> |
  <a href="https://github.com/duy7590">GitHub</a>
  </p>
  
  <p align="justify">
  Data Analyst at Catapult International.
  <br><br>
  Currently a master student in computational data analysis with a background in finance and 3-year experience working in financial services. 
  I am keen on working with big data processing (hadoop apache spark) and Machine learning using Python and its packages, i.e., numpy, scipy, pandas,scikit-learn, scikit-image etc. I also have experience in database query language such as SQL and Data visualization using Tableau. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
