title: <p align="center"> Duy Nguyen  Helsinki, Finland </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/duynguyen7590/">LinkedIn</a> |
  <a href="https://github.com/duy7590">GitHub</a>
  </p>
  
  <p align="justify">
  Data Analyst at Catapult International.
  <br><br>
  Currently a master student in computational data analysis in Tampere University with a background in finance. I've accumulated 3-year experience working in financial services and 3-years as Data Analyst and research consultant in Catapult Inernational Oy where I have developed my business intelligence expertise by utilizing different data sources (both public data sources and private databases) and visualization tools to provide the insight for big Nordic corporate clients in technologies & venture capital market to consult their strategic decisions in digitalization & innovation plan. I am keen on working with large dataset processing, analysis and especially stories telling skills which communicate the complexity into simplicity to support different managment levels. I can also perform a variety of ML tasks using Python and its packages, i.e., numpy, scipy, pandas, matplotlib, seaborn, scikit-learn, scikit-image etc. I also have experience in database query language such as SQL (SQL Server) and Data visualization using Tableau, Power BI....and of course, i am highly skilled in uing Excel asl well.<br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
